import './js/html-theme';
import './js/mobile-menu';
import './js/drop-down';
import './js/drop-down-modal';
import './js/random-cocktails';
import './js/page-scroll';
import './js/coctails-search';
import './js/favorite-cocktails';
import './js/plagination';
